"""
create_fodo_yellow_pages.py
============================
Generate fodo_yellow_pages_lookup_table.yml for the FODO test facility.

Mirrors create_yellow_pages_lut_from_config() in
  scripts/bessyii/create_managers_input.py
but is derived directly from the FODO magnet database
(custom_epics/data/fodo/accelerator_setup.json, itself generated by
json2accelerator_setup_fodo.py) instead of a separate magnets.yaml,
since FODO has no such input config.

Output keys (same shape as the BESSY II yellow pages lookup table):
  quadrupoles, sextupoles, steerers,
  horizontal_steerers, horizontal_steerers_host,
  vertical_steerers, vertical_steerers_host,
  cavities

horizontal_steerers_host / vertical_steerers_host name the underlying
AT Multipole lattice element each steerer acts on (e.g. "COR_001" for
both "HCOR_001" and "VCOR_001" — a steerer is the corrector coil, the
host is the single AT element both planes' kicks live on). There's no
separate "multipole magnet" family: unlike BESSY II, where the host is
an existing Quadrupole/Sextupole, FODO's host has no power converter
of its own and never appears in accelerator_setup.json.
"""

import datetime
import json
from pathlib import Path

import yaml

FODO_DIR = Path(__file__).resolve().parent.parent
ACCELERATOR_SETUP_FILE = (
    FODO_DIR.parent.parent / "custom_epics" / "data" / "fodo" / "accelerator_setup.json"
)
LATTICE_FILE = FODO_DIR / "resources" / "fodo_lattice.json"
OUTPUT_FILE = FODO_DIR / "resources" / "created" / "fodo_yellow_pages_lookup_table.yml"


class CompressedSequenceDumper(yaml.SafeDumper):
    def represent_sequence(self, tag, seq, flow_style=None):
        flow = len(seq) <= 12
        return super().represent_sequence(tag, seq, flow_style=flow)


def build_yellow_pages_lut(magnets, lattice_elements):
    quadrupoles = [m["name"] for m in magnets if m["type"] == "Quadrupole"]
    sextupoles = [m["name"] for m in magnets if m["type"] == "Sextupole"]
    steerers = [m["name"] for m in magnets if m["type"] == "Steerer"]

    horizontal_steerers = [s for s in steerers if s.startswith("H")]
    vertical_steerers = [s for s in steerers if s.startswith("V")]
    horizontal_steerers_host = [s[1:] for s in horizontal_steerers]
    vertical_steerers_host = [s[1:] for s in vertical_steerers]

    # Cavities aren't power-converter-driven magnets, so they don't appear
    # in accelerator_setup.json; take their names from the AT lattice.
    cavities = [e["FamName"] for e in lattice_elements if e.get("Class") == "RFCavity"]

    return dict(
        quadrupoles=quadrupoles,
        sextupoles=sextupoles,
        steerers=steerers,
        horizontal_steerers=horizontal_steerers,
        horizontal_steerers_host=horizontal_steerers_host,
        vertical_steerers=vertical_steerers,
        vertical_steerers_host=vertical_steerers_host,
        cavities=cavities,
    )


def main():
    with ACCELERATOR_SETUP_FILE.open() as f:
        magnets = json.load(f)
    with LATTICE_FILE.open() as f:
        lattice = json.load(f)

    yp_lut = build_yellow_pages_lut(magnets, lattice["elements"])

    header = (
        "# \n"
        f"# FODO yellow pages: {datetime.datetime.now()}\n"
        "# WARNING: automatically generated data\n"
        "#          please check when it is updated if you edit it by hand!\n"
    )

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_FILE.open("wt") as f:
        f.write(header)
        yaml.dump(yp_lut, f, Dumper=CompressedSequenceDumper)
        f.write("# EOF\n")

    print("Generated yellow pages entries:")
    for k, v in yp_lut.items():
        print(f"  {k:26s}: {len(v)}")
    print(f"\nWritten to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
