[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"

[project]
name = "dt4acc"
version = "0.3.0"
description = "digital twin for accelerators"
authors = [
  { name = "Waheedullah Sulaiman Khail" },
  { name = "Pierre Schnizer" },
]
license = { text = "GPL-3.0" }
requires-python = ">=3.7"
keywords = []
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: GNU General Public License (GPL)",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Physics",
]

dependencies = [
    "dt4acc-lib>=0.4",
    # for BESSY II
    # actually required by custom bessyii
    # currently bessyii load managers used by
    # soleil too...
    # these depend on yaml
    "pyaml",
    "pydantic",
]

# Todo: fix that I don't need to give a specific path

[project.urls]
Homepage = "https://github.com/dt4acc/dt4acc"
Documentation = "https://github.com/dt4acc/dt4acc"
Repository = "https://github.com/dt4acc/dt4acc.git"

[project.optional-dependencies]
docs = [
  "Sphinx",
  "sphinx-rtd-theme",
  "sphinxcontrib-napoleon",
  "furo",
  "myst-parser",
  "sphinx-autodoc-typehints>=2.0",
  "sphinx-copybutton",
  "sphinx-design",
  "sphinxcontrib-bibtex",
  "numpydoc",
]

epics = [
     "softioc>4.1",
     "p4p"
]

tango = [
     "pytango!=10.1.*"
]

bessyii = [
    "lat2db"
]
[project.scripts]
dt4acc_bessyii = "dt4acc.custom_facility.bessyii.run_bessyii_twin:main"
dt4acc_soleil = "dt4acc.custom_facility.soleil.run_soleil_twin:main"
dt4acc_maxiv = "dt4acc.custom_facility.maxiv.run_maxiv_twin:main"

[tool.hatch.build.targets.wheel]
packages = ["src/dt4acc"]

[tool.hatch.build]
dev-mode-dirs = ["src"]