[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dt4acc"
version = "0.1.0"
description = "digital twin for accelerators"
authors = [  "Waheedullah Sulaiman Khail", "Pierre Schnizer"]
license = "GPL-3.0"
homepage = "https://github.com/hz-b/dt4acc"
documentation = "https://github.com/hz-b/dt4acc"
repository = "https://github.com/hz-b/dt4acc.git"
keywords = []
classifiers = [
     "Development Status :: 4 - Beta",
     "Intended Audience :: Science/Research",
     "License :: OSI Approved :: GNU General Public License (GPL)",
     "Programming Language :: Python :: 3",
     "Topic :: Scientific/Engineering :: Physics"
]

[tool.poetry.scripts]
dt4acc_softioc = { reference = "scripts/dt4acc_softioc.py", type = "file"}

[tool.poetry.dependencies]
python = ">=3.7"
accelerator-toolbox="*"
numpy="<2.0"
pymongo="*"
pandas="*"

# HZB modules providing different functionallity
# to be replaced by accml or similar
lat2db="*"
bact_device_models="*"
bact-twin-architecture="*"

# if using epics
# waveforms of chars/strings
softioc = {version = ">4.1", optional = true }
p4p = {version = "*",  optional = true }
# if ussing tango
pytango = {version = "*", optional = true }

# jsons="*"
# fastapi="*"
# pydantic="*"
#
# uuid="*"pymongo
# pytest="*"
# attrs="*"
# uvicorn="*"
# httpx="*"
# lark="*"

# for documentation build
Sphinx = { version = "4.2.0", optional = true }
sphinx-rtd-theme = { version = "1.0.0", optional = true }
sphinxcontrib-napoleon = { version = "0.7", optional = true }

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme", "sphinxcontrib-napoleon"]
epics = [ "softioc", "p4p" ]
tango = [ "pytango" ]