[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dt4acc"
version = "0.0.3"
description = "digital twin for accelerators"
authors = [  "Waheedullah Sulaiman Khail", "Pierre Schnizer"]
license = "GPL-3.0"
homepage = "https://github.com/hz-b/dt4acc"
documentation = "https://github.com/hz-b/dt4acc"
repository = "https://github.com/hz-b/dt4acc.git"
keywords = []
classifiers = [
     "Development Status :: 4 - Beta",
     "Intended Audience :: Science/Research",
     "License :: OSI Approved :: GNU General Public License (GPL)",
     "Programming Language :: Python :: 3",
     "Topic :: Scientific/Engineering :: Physics"
]

[tool.poetry.dependencies]
python = ">=3.7"
accelerator-toolbox="*"
numpy="<2.0"
pymongo="*"
lat2db="*"
# waveforms of chars/strings
softioc=">4.1"

p4p="*"
bact_device_models="*"
pandas="*"
bact-twin-architecture="*"
# jsons="*"
# fastapi="*"
# pydantic="*"
#
# uuid="*"pymongo
# pytest="*"
# attrs="*"
# uvicorn="*"
# httpx="*"
# lark="*"
Sphinx = { version = "4.2.0", optional = true }
sphinx-rtd-theme = { version = "1.0.0", optional = true }
sphinxcontrib-napoleon = { version = "0.7", optional = true }

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme", "sphinxcontrib-napoleon"]
