[pytest]
testpaths =
    src/dt4acc/custom_tango/tests
    src/dt4acc/custom_epics/tests

markers =
    integration: requires a running server
    slow: writes to devices and waits
    connectivity: basic reachability checks

log_cli = true
log_cli_level = WARNING
timeout = 30