#!/usr/bin/env python3
"""
run_maxiv_r1_twin.py
====================
Launch script for the MAX IV R1 digital twin TANGO server.

Usage
-----
    dt4acc_maxiv_r1                                  # installed entry point
    python run_maxiv_r1_twin.py                      # direct
    python run_maxiv_r1_twin.py --lattice PATH       # custom lattice
    python run_maxiv_r1_twin.py --heartbeat-period 0 # disable heartbeat

Configuration data directory
-----------------------------
    ~/Documents/dt4acc_config_data/

    This is a facility-agnostic path — only one facility twin runs per machine,
    so no facility-specific subdirectory is needed.

    Expected files:
        accelerator_setup.json    ← magnet DB (generated by json2accelerator_setup_maxiv_r1.py)
        R1_lattice.json           ← AT lattice (JSON format, atjson v1) — default name
                                    Override with --lattice

Environment variables (all optional, CLI args take precedence)
--------------------------------------------------------------
    DT4ACC_LATTICE_FILE   Path to the MAX IV R1 AT lattice JSON file
    DT4ACC_TANGO_HOST     Tango database host:port  (default: localhost:10000)
    DT4ACC_VIEW           view mode: "device" for MAX IV (default: device)
"""

import argparse
import os
import sys
from pathlib import Path

from dt4acc.custom_tango.ioc import handle_lattice

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

DATA_DIR = Path.home() / "Documents" / "dt4acc_config_data"

DEFAULT_LATTICE_FILE = DATA_DIR / "R1_lat_indexed.json"

DEFAULT_HEARTBEAT_PERIOD_S = 1.0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(
        description="Launch the MAX IV R1 digital twin TANGO server"
    )
    parser.add_argument(
        "--lattice",
        type=Path,
        default=Path(os.environ.get("DT4ACC_LATTICE_FILE", DEFAULT_LATTICE_FILE)),
        help=f"Path to the MAX IV R1 AT lattice JSON file (default: {DEFAULT_LATTICE_FILE})",
    )
    parser.add_argument(
        "--tango-host",
        default=os.environ.get("DT4ACC_TANGO_HOST", "localhost:10000"),
        help="Tango database host:port (default: localhost:10000)",
    )
    parser.add_argument(
        "--heartbeat-period",
        type=float,
        default=DEFAULT_HEARTBEAT_PERIOD_S,
        help=f"Recalculation period in seconds, 0 to disable (default: {DEFAULT_HEARTBEAT_PERIOD_S})",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=50200,
        help="TCP port for the MexecService manager (default: 50200)",
    )
    parser.add_argument(
        "--view",
        type=str,
        default=os.environ.get("DT4ACC_VIEW", "device"),
        help="View mode: 'device' (MAX IV default) or 'design' (default: device)",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# MAX IV R1 load_managers
# ---------------------------------------------------------------------------

def _maxiv_r1_load_managers():
    """Load the MAX IV R1 liaison manager and translator service."""
    from dt4acc.custom_facility.maxiv.liasion_translator_setup import load_managers
    return load_managers()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    args = parse_args()

    if not args.lattice.exists():
        print(f"ERROR: Lattice file not found: {args.lattice}", file=sys.stderr)
        print(
            f"       Copy R1_lat_indexed.json to {DATA_DIR}/ or pass --lattice PATH",
            file=sys.stderr,
        )
        sys.exit(1)

    print("MAX IV R1 twin server starting")
    print(f"  Lattice          : {args.lattice}")
    print(f"  Config data      : {DATA_DIR}")
    print(f"  TANGO            : {args.tango_host}")
    print(f"  Recalc period    : {args.heartbeat_period}s (no lattice changes)")
    print(f"  MexecPort        : {args.port}")
    print(f"  View             : {args.view}")

    os.environ["TANGO_HOST"] = args.tango_host

    from dt4acc.custom_tango.ioc import server_manager
    from dt4acc.custom_tango.ioc.single_server import enable_device_view_readback
    enable_device_view_readback()

    handle_lattice.lattice_loader.set_lattice_file(args.lattice)
    server_manager.LOAD_MANAGERS_FN = _maxiv_r1_load_managers
    server_manager.HEARTBEAT_PERIOD = args.heartbeat_period
    server_manager._MANAGER_PORT    = args.port
    server_manager.EXPECTED_VIEW    = args.view

    server_manager.main()


if __name__ == "__main__":
    main()