file db/muxer_elements.rec
{
	pattern	 {ELEMENT }
#start of quadrupoles
		{ q1m1d1r } 
		{ q1m1d2r } 
		{ q1m1d3r } 
		{ q1m1d4r } 
		{ q1m1d5r } 
		{ q1m1d6r } 
		{ q1m1d7r } 
		{ q1m1d8r } 

		{ q1m1t1r } 
		{ q1m1t2r } 
		{ q1m1t3r } 
		{ q1m1t4r } 
		{ q1m1t5r } 
		{ q1m1t6r } 
		{ q1m1t7r } 
		{ q1m1t8r } 


# .2d
		{ q1m2d1r } 
		{ q1m2d2r } 
		{ q1m2d3r } 
		{ q1m2d4r } 
		{ q1m2d5r } 
		{ q1m2d6r } 
		{ q1m2d7r } 
		{ q1m2d8r } 

		{ q1m2t1r } 
		{ q1m2t2r } 
		{ q1m2t3r } 
		{ q1m2t4r } 
		{ q1m2t5r } 
		{ q1m2t6r } 
		{ q1m2t7r } 
		{ q1m2t8r } 


# .1d
		{ q2m1d1r } 
		{ q2m1d2r } 
		{ q2m1d3r } 
		{ q2m1d4r } 
		{ q2m1d5r } 
		{ q2m1d6r } 
		{ q2m1d7r } 
		{ q2m1d8r } 

		{ q2m1t1r } 
		{ q2m1t2r } 
		{ q2m1t3r } 
		{ q2m1t4r } 
		{ q2m1t5r } 
		{ q2m1t6r } 
		{ q2m1t7r } 
		{ q2m1t8r } 


# .2d
		{ q2m2d1r } 
		{ q2m2d2r } 
		{ q2m2d3r } 
		{ q2m2d4r } 
		{ q2m2d5r } 
		{ q2m2d6r } 
		{ q2m2d7r } 
		{ q2m2d8r } 

		{ q2m2t1r } 
		{ q2m2t2r } 
		{ q2m2t3r } 
		{ q2m2t4r } 
		{ q2m2t5r } 
		{ q2m2t6r } 
		{ q2m2t7r } 
		{ q2m2t8r } 


# .1d
		{ q3m1d1r } 
		{ q3m1d2r } 
		{ q3m1d3r } 
		{ q3m1d4r } 
		{ q3m1d5r } 
		{ q3m1d6r } 
		{ q3m1d7r } 
		{ q3m1d8r } 

		{ q3m1t1r } 
		{ q3m1t2r } 
		{ q3m1t3r } 
		{ q3m1t4r } 
		{ q3m1t5r } 
		{ q3m1t6r } 
		{ q3m1t7r } 
		{ q3m1t8r } 


# .2d
		{ q3m2d1r } 
		{ q3m2d2r } 
		{ q3m2d3r } 
		{ q3m2d4r } 
		{ q3m2d5r } 
		{ q3m2d6r } 
		{ q3m2d7r } 
		{ q3m2d8r } 

		{ q3m2t1r } 
		{ q3m2t2r } 
		{ q3m2t3r } 
		{ q3m2t4r } 
		{ q3m2t5r } 
		{ q3m2t6r } 
		{ q3m2t7r } 
		{ q3m2t8r } 


# .1d
		{ q4m1d1r } 
		{ q4m1d2r } 
		{ q4m1d3r } 
		{ q4m1d4r } 
		{ q4m1d5r } 
		{ q4m1d6r } 
		{ q4m1d7r } 
		{ q4m1d8r } 

		{ q4m1t1r } 
		{ q4m1t2r } 
		{ q4m1t3r } 
		{ q4m1t4r } 
		{ q4m1t5r } 
		{ q4m1t6r } 
		{ q4m1t7r } 
		{ q4m1t8r } 


# .2d
		{ q4m2d1r } 
		{ q4m2d2r } 
		{ q4m2d3r } 
		{ q4m2d4r } 
		{ q4m2d5r } 
		{ q4m2d6r } 
		{ q4m2d7r } 
		{ q4m2d8r } 

		{ q4m2t1r } 
		{ q4m2t2r } 
		{ q4m2t3r } 
		{ q4m2t4r } 
		{ q4m2t5r } 
		{ q4m2t6r } 
		{ q4m2t7r } 
		{ q4m2t8r } 

# .1t
		{ q5m1t1r } 
		{ q5m1t2r } 
		{ q5m1t3r } 
		{ q5m1t4r } 
		{ q5m1t5r } 
		{ q5m1t6r } 
		{ q5m1t7r } 
		{ q5m1t8r } 

# .2t
		{ q5m2t1r } 
		{ q5m2t2r } 
		{ q5m2t3r } 
		{ q5m2t4r } 
		{ q5m2t5r } 
		{ q5m2t6r } 
		{ q5m2t7r } 
		{ q5m2t8r } 
# end of quadrupoles


#start of horizontal_steerers
		{ hs1md1r  } 
		{ hs1md2r  } 
		{ hs1md3r  } 
		{ hs1md4r  } 
		{ hs1md5r  } 
		{ hs1md6r  } 
		{ hs1md7r  } 
		{ hs1md8r  } 

		{ hs1mt1r  } 
		{ hs1mt2r  } 
		{ hs1mt3r  } 
		{ hs1mt4r  } 
		{ hs1mt5r  } 
		{ hs1mt6r  } 
		{ hs1mt7r  } 
		{ hs1mt8r  } 



# hs4m1d
		{ hs4m1d1r } 
		{ hs4m1d2r } 
		{ hs4m1d3r } 
		{ hs4m1d4r } 
		{ hs4m1d5r } 
		{ hs4m1d6r } 
		{ hs4m1d7r } 
		{ hs4m1d8r } 

		{ hs4m1t1r } 
		{ hs4m1t2r } 
		{ hs4m1t3r } 
		{ hs4m1t4r } 
		{ hs4m1t5r } 
		{ hs4m1t6r } 
		{ hs4m1t7r } 
		{ hs4m1t8r } 


# hs4m2d
		{ hs4m2d1r } 
		{ hs4m2d2r } 
		{ hs4m2d3r } 
		{ hs4m2d4r } 
		{ hs4m2d5r } 
		{ hs4m2d6r } 
		{ hs4m2d7r } 
		{ hs4m2d8r } 

		{ hs4m2t1r } 
		{ hs4m2t2r } 
		{ hs4m2t3r } 
		{ hs4m2t4r } 
		{ hs4m2t5r } 
		{ hs4m2t6r } 
		{ hs4m2t7r } 
		{ hs4m2t8r } 
# end of horizontal_steerers


#start of vertical_steerers
		{ vs2m1d1r } 
		{ vs2m1d2r } 
		{ vs2m1d3r } 
		{ vs2m1d4r } 
		{ vs2m1d5r } 
		{ vs2m1d6r } 
		{ vs2m1d7r } 
		{ vs2m1d8r } 

		{ vs2m1t1r } 
		{ vs2m1t2r } 
		{ vs2m1t3r } 
		{ vs2m1t4r } 
		{ vs2m1t5r } 
		{ vs2m1t6r } 
		{ vs2m1t7r } 
		{ vs2m1t8r } 


# vs2m2d
		{ vs2m2d1r } 
		{ vs2m2d2r } 
		{ vs2m2d3r } 
		{ vs2m2d4r } 
		{ vs2m2d5r } 
		{ vs2m2d6r } 
		{ vs2m2d7r } 
		{ vs2m2d8r } 

		{ vs2m2t1r } 
		{ vs2m2t2r } 
		{ vs2m2t3r } 
		{ vs2m2t4r } 
		{ vs2m2t5r } 
		{ vs2m2t6r } 
		{ vs2m2t7r } 
		{ vs2m2t8r } 



# vs3m1d
		{ vs3m1d1r } 
		{ vs3m1d2r } 
		{ vs3m1d3r } 
		{ vs3m1d4r } 
		{ vs3m1d5r } 
		{ vs3m1d6r } 
		{ vs3m1d7r } 
		{ vs3m1d8r } 

		{ vs3m1t1r } 
		{ vs3m1t2r } 
		{ vs3m1t3r } 
		{ vs3m1t4r } 
		{ vs3m1t5r } 
		{ vs3m1t6r } 
		{ vs3m1t7r } 
		{ vs3m1t8r } 


# vs3m2d
		{ vs3m2d1r } 
		{ vs3m2d2r } 
		{ vs3m2d3r } 
		{ vs3m2d4r } 
		{ vs3m2d5r } 
		{ vs3m2d6r } 
		{ vs3m2d7r } 
		{ vs3m2d8r } 

		{ vs3m2t1r } 
		{ vs3m2t2r } 
		{ vs3m2t3r } 
		{ vs3m2t4r } 
		{ vs3m2t5r } 
		{ vs3m2t6r } 
		{ vs3m2t7r } 
		{ vs3m2t8r } 
# end of vertical_steerers
}
# EOF
