file db/offset.rec
{
	pattern {ELEMENT}
#start of quadrupoles
		{ Q1M2D1R }


# .1T
		{ Q1M1T1R }

# .2T
		{ Q1M2T1R }


# .1D
		{ Q1M1D2R }

# .2D
		{ Q1M2D2R }


# .1T
		{ Q1M1T2R }

# .2T
		{ Q1M2T2R }


# .1D
		{ Q1M1D3R }

# .2D
		{ Q1M2D3R }


# .1T
		{ Q1M1T3R }

# .2T
		{ Q1M2T3R }


# .1D
		{ Q1M1D4R }

# .2D
		{ Q1M2D4R }


# .1T
		{ Q1M1T4R }

# .2T
		{ Q1M2T4R }


# .1D
		{ Q1M1D5R }

# .2D
		{ Q1M2D5R }


# .1T
		{ Q1M1T5R }

# .2T
		{ Q1M2T5R }


# .1D
		{ Q1M1D6R }

# .2D
		{ Q1M2D6R }


# .1T
		{ Q1M1T6R }

# .2T
		{ Q1M2T6R }


# .1D
		{ Q1M1D7R }

# .2D
		{ Q1M2D7R }


# .1T
		{ Q1M1T7R }

# .2T
		{ Q1M2T7R }


# .1D
		{ Q1M1D8R }

# .2D
		{ Q1M2D8R }


# .1T
		{ Q1M1T8R }

# .2T
		{ Q1M2T8R }


# .1D
		{ Q1M1D1R }

# .2D
		{ Q2M2D1R }


# .1T
		{ Q2M1T1R }

# .2T
		{ Q2M2T1R }


# .1D
		{ Q2M1D2R }

# .2D
		{ Q2M2D2R }


# .1T
		{ Q2M1T2R }

# .2T
		{ Q2M2T2R }


# .1D
		{ Q2M1D3R }

# .2D
		{ Q2M2D3R }


# .1T
		{ Q2M1T3R }

# .2T
		{ Q2M2T3R }


# .1D
		{ Q2M1D4R }

# .2D
		{ Q2M2D4R }


# .1T
		{ Q2M1T4R }

# .2T
		{ Q2M2T4R }


# .1D
		{ Q2M1D5R }

# .2D
		{ Q2M2D5R }


# .1T
		{ Q2M1T5R }

# .2T
		{ Q2M2T5R }


# .1D
		{ Q2M1D6R }

# .2D
		{ Q2M2D6R }


# .1T
		{ Q2M1T6R }

# .2T
		{ Q2M2T6R }


# .1D
		{ Q2M1D7R }

# .2D
		{ Q2M2D7R }


# .1T
		{ Q2M1T7R }

# .2T
		{ Q2M2T7R }


# .1D
		{ Q2M1D8R }

# .2D
		{ Q2M2D8R }


# .1T
		{ Q2M1T8R }

# .2T
		{ Q2M2T8R }


# .1D
		{ Q2M1D1R }

# .2D
		{ Q3M2D1R }


# .1T
		{ Q3M1T1R }

# .2T
		{ Q3M2T1R }


# .1D
		{ Q3M1D2R }

# .2D
		{ Q3M2D2R }


# .1T
		{ Q3M1T2R }

# .2T
		{ Q3M2T2R }


# .1D
		{ Q3M1D3R }

# .2D
		{ Q3M2D3R }


# .1T
		{ Q3M1T3R }

# .2T
		{ Q3M2T3R }


# .1D
		{ Q3M1D4R }

# .2D
		{ Q3M2D4R }


# .1T
		{ Q3M1T4R }

# .2T
		{ Q3M2T4R }


# .1D
		{ Q3M1D5R }

# .2D
		{ Q3M2D5R }


# .1T
		{ Q3M1T5R }

# .2T
		{ Q3M2T5R }


# .1D
		{ Q3M1D6R }

# .2D
		{ Q3M2D6R }


# .1T
		{ Q3M1T6R }

# .2T
		{ Q3M2T6R }


# .1D
		{ Q3M1D7R }

# .2D
		{ Q3M2D7R }


# .1T
		{ Q3M1T7R }

# .2T
		{ Q3M2T7R }


# .1D
		{ Q3M1D8R }

# .2D
		{ Q3M2D8R }


# .1T
		{ Q3M1T8R }

# .2T
		{ Q3M2T8R }


# .1D
		{ Q3M1D1R }

# .2D
		{ Q4M2D1R }


# .1T
		{ Q4M1T1R }

# .2T
		{ Q4M2T1R }


# .1D
		{ Q4M1D2R }

# .2D
		{ Q4M2D2R }


# .1T
		{ Q4M1T2R }

# .2T
		{ Q4M2T2R }


# .1D
		{ Q4M1D3R }

# .2D
		{ Q4M2D3R }


# .1T
		{ Q4M1T3R }

# .2T
		{ Q4M2T3R }


# .1D
		{ Q4M1D4R }

# .2D
		{ Q4M2D4R }


# .1T
		{ Q4M1T4R }

# .2T
		{ Q4M2T4R }


# .1D
		{ Q4M1D5R }

# .2D
		{ Q4M2D5R }


# .1T
		{ Q4M1T5R }

# .2T
		{ Q4M2T5R }


# .1D
		{ Q4M1D6R }

# .2D
		{ Q4M2D6R }


# .1T
		{ Q4M1T6R }

# .2T
		{ Q4M2T6R }


# .1D
		{ Q4M1D7R }

# .2D
		{ Q4M2D7R }


# .1T
		{ Q4M1T7R }

# .2T
		{ Q4M2T7R }


# .1D
		{ Q4M1D8R }

# .2D
		{ Q4M2D8R }


# .1T
		{ Q4M1T8R }

# .2T
		{ Q4M2T8R }


# .1D
		{ Q4M1D1R }

		{ Q5M1T1R }

# .2T
		{ Q5M2T1R }

# .1T
		{ Q5M1T2R }

# .2T
		{ Q5M2T2R }

# .1T
		{ Q5M1T3R }

# .2T
		{ Q5M2T3R }

# .1T
		{ Q5M1T4R }

# .2T
		{ Q5M2T4R }

# .1T
		{ Q5M1T5R }

# .2T
		{ Q5M2T5R }

# .1T
		{ Q5M1T6R }

# .2T
		{ Q5M2T6R }

# .1T
		{ Q5M1T7R }

# .2T
		{ Q5M2T7R }

# .1T
		{ Q5M1T8R }

# .2T
		{ Q5M2T8R }


# QITT
		{ QIT6 }
# end of quadrupoles
}
# EOF
