file db/power_converter_relay.rec
{
	pattern {PC, ELEMENT}
#start of quadrupoles
		{ Q1PDR, q1m1d1r } 
		{ Q1PDR, q1m1d2r } 
		{ Q1PDR, q1m1d3r } 
		{ Q1PDR, q1m1d4r } 
		{ Q1PDR, q1m1d5r } 
		{ Q1PDR, q1m1d6r } 
		{ Q1PDR, q1m1d7r } 
		{ Q1PDR, q1m1d8r } 

		{ Q1PTR, q1m1t1r } 
		{ Q1PTR, q1m1t2r } 
		{ Q1PTR, q1m1t3r } 
		{ Q1PTR, q1m1t4r } 
		{ Q1PTR, q1m1t5r } 
		{ Q1PTR, q1m1t6r } 
		{ Q1PTR, q1m1t7r } 
		{ Q1PTR, q1m1t8r } 


# .2d
		{ Q1PDR, q1m2d1r } 
		{ Q1PDR, q1m2d2r } 
		{ Q1PDR, q1m2d3r } 
		{ Q1PDR, q1m2d4r } 
		{ Q1PDR, q1m2d5r } 
		{ Q1PDR, q1m2d6r } 
		{ Q1PDR, q1m2d7r } 
		{ Q1PDR, q1m2d8r } 

		{ Q1PTR, q1m2t1r } 
		{ Q1PTR, q1m2t2r } 
		{ Q1PTR, q1m2t3r } 
		{ Q1PTR, q1m2t4r } 
		{ Q1PTR, q1m2t5r } 
		{ Q1PTR, q1m2t6r } 
		{ Q1PTR, q1m2t7r } 
		{ Q1PTR, q1m2t8r } 


# .1d
		{ Q2PDR, q2m1d1r } 
		{ Q2PDR, q2m1d2r } 
		{ Q2PDR, q2m1d3r } 
		{ Q2PDR, q2m1d4r } 
		{ Q2PDR, q2m1d5r } 
		{ Q2PDR, q2m1d6r } 
		{ Q2PDR, q2m1d7r } 
		{ Q2PDR, q2m1d8r } 

		{ Q2PTR, q2m1t1r } 
		{ Q2PTR, q2m1t2r } 
		{ Q2PTR, q2m1t3r } 
		{ Q2PTR, q2m1t4r } 
		{ Q2PTR, q2m1t5r } 
		{ Q2PTR, q2m1t6r } 
		{ Q2PTR, q2m1t7r } 
		{ Q2PTR, q2m1t8r } 


# .2d
		{ Q2PDR, q2m2d1r } 
		{ Q2PDR, q2m2d2r } 
		{ Q2PDR, q2m2d3r } 
		{ Q2PDR, q2m2d4r } 
		{ Q2PDR, q2m2d5r } 
		{ Q2PDR, q2m2d6r } 
		{ Q2PDR, q2m2d7r } 
		{ Q2PDR, q2m2d8r } 

		{ Q2PTR, q2m2t1r } 
		{ Q2PTR, q2m2t2r } 
		{ Q2PTR, q2m2t3r } 
		{ Q2PTR, q2m2t4r } 
		{ Q2PTR, q2m2t5r } 
		{ Q2PTR, q2m2t6r } 
		{ Q2PTR, q2m2t7r } 
		{ Q2PTR, q2m2t8r } 


# .1d
		{ Q3PD1R, q3m1d1r } 
		{ Q3PD2R, q3m1d2r } 
		{ Q3PD3R, q3m1d3r } 
		{ Q3PD4R, q3m1d4r } 
		{ Q3PD5R, q3m1d5r } 
		{ Q3PD6R, q3m1d6r } 
		{ Q3PD7R, q3m1d7r } 
		{ Q3PD8R, q3m1d8r } 

		{ Q3P1T1R, q3m1t1r } 
		{ Q3PT2R, q3m1t2r } 
		{ Q3PT3R, q3m1t3r } 
		{ Q3PT4R, q3m1t4r } 
		{ Q3PT5R, q3m1t5r } 
		{ Q3P1T6R, q3m1t6r } 
		{ Q3PT7R, q3m1t7r } 
		{ Q3P1T8R, q3m1t8r } 


# .2d
		{ Q3PD1R, q3m2d1r } 
		{ Q3PD2R, q3m2d2r } 
		{ Q3PD3R, q3m2d3r } 
		{ Q3PD4R, q3m2d4r } 
		{ Q3PD5R, q3m2d5r } 
		{ Q3PD6R, q3m2d6r } 
		{ Q3PD7R, q3m2d7r } 
		{ Q3PD8R, q3m2d8r } 

		{ Q3P2T1R, q3m2t1r } 
		{ Q3PT2R, q3m2t2r } 
		{ Q3PT3R, q3m2t3r } 
		{ Q3PT4R, q3m2t4r } 
		{ Q3PT5R, q3m2t5r } 
		{ Q3P2T6R, q3m2t6r } 
		{ Q3PT7R, q3m2t7r } 
		{ Q3P2T8R, q3m2t8r } 


# .1d
		{ Q4PD1R, q4m1d1r } 
		{ Q4PD2R, q4m1d2r } 
		{ Q4PD3R, q4m1d3r } 
		{ Q4PD4R, q4m1d4r } 
		{ Q4PD5R, q4m1d5r } 
		{ Q4PD6R, q4m1d6r } 
		{ Q4PD7R, q4m1d7r } 
		{ Q4PD8R, q4m1d8r } 

		{ Q4P1T1R, q4m1t1r } 
		{ Q4PT2R, q4m1t2r } 
		{ Q4PT3R, q4m1t3r } 
		{ Q4PT4R, q4m1t4r } 
		{ Q4PT5R, q4m1t5r } 
		{ Q4P1T6R, q4m1t6r } 
		{ Q4PT7R, q4m1t7r } 
		{ Q4P1T8R, q4m1t8r } 


# .2d
		{ Q4PD1R, q4m2d1r } 
		{ Q4PD2R, q4m2d2r } 
		{ Q4PD3R, q4m2d3r } 
		{ Q4PD4R, q4m2d4r } 
		{ Q4PD5R, q4m2d5r } 
		{ Q4PD6R, q4m2d6r } 
		{ Q4PD7R, q4m2d7r } 
		{ Q4PD8R, q4m2d8r } 

		{ Q4P2T1R, q4m2t1r } 
		{ Q4PT2R, q4m2t2r } 
		{ Q4PT3R, q4m2t3r } 
		{ Q4PT4R, q4m2t4r } 
		{ Q4PT5R, q4m2t5r } 
		{ Q4P2T6R, q4m2t6r } 
		{ Q4PT7R, q4m2t7r } 
		{ Q4P2T8R, q4m2t8r } 

# .1t
		{ Q5P1T1R, q5m1t1r } 
		{ Q5PT2R, q5m1t2r } 
		{ Q5PT3R, q5m1t3r } 
		{ Q5PT4R, q5m1t4r } 
		{ Q5PT5R, q5m1t5r } 
		{ Q5P1T6R, q5m1t6r } 
		{ Q5PT7R, q5m1t7r } 
		{ Q5P1T8R, q5m1t8r } 

# .2t
		{ Q5P2T1R, q5m2t1r } 
		{ Q5PT2R, q5m2t2r } 
		{ Q5PT3R, q5m2t3r } 
		{ Q5PT4R, q5m2t4r } 
		{ Q5PT5R, q5m2t5r } 
		{ Q5P2T6R, q5m2t6r } 
		{ Q5PT7R, q5m2t7r } 
		{ Q5P2T8R, q5m2t8r } 
# end of quadrupoles


#start of horizontal_steerers
		{ HS1PD1R, hs1md1r  } 
		{ HS1PD2R, hs1md2r  } 
		{ HS1PD3R, hs1md3r  } 
		{ HS1PD4R, hs1md4r  } 
		{ HS1PD5R, hs1md5r  } 
		{ HS1PD6R, hs1md6r  } 
		{ HS1PD7R, hs1md7r  } 
		{ HS1PD8R, hs1md8r  } 

		{ HS1PT1R, hs1mt1r  } 
		{ HS1PT2R, hs1mt2r  } 
		{ HS1PT3R, hs1mt3r  } 
		{ HS1PT4R, hs1mt4r  } 
		{ HS1PT5R, hs1mt5r  } 
		{ HS1PT6R, hs1mt6r  } 
		{ HS1PT7R, hs1mt7r  } 
		{ HS1PT8R, hs1mt8r  } 



# hs4m1d
		{ HS4P1D1R, hs4m1d1r } 
		{ HS4P1D2R, hs4m1d2r } 
		{ HS4P1D3R, hs4m1d3r } 
		{ HS4P1D4R, hs4m1d4r } 
		{ HS4P1D5R, hs4m1d5r } 
		{ HS4P1D6R, hs4m1d6r } 
		{ HS4P1D7R, hs4m1d7r } 
		{ HS4P1D8R, hs4m1d8r } 

		{ HS4P1T1R, hs4m1t1r } 
		{ HS4P1T2R, hs4m1t2r } 
		{ HS4P1T3R, hs4m1t3r } 
		{ HS4P1T4R, hs4m1t4r } 
		{ HS4P1T5R, hs4m1t5r } 
		{ HS4P1T6R, hs4m1t6r } 
		{ HS4P1T7R, hs4m1t7r } 
		{ HS4P1T8R, hs4m1t8r } 


# hs4m2d
		{ HS4P2D1R, hs4m2d1r } 
		{ HS4P2D2R, hs4m2d2r } 
		{ HS4P2D3R, hs4m2d3r } 
		{ HS4P2D4R, hs4m2d4r } 
		{ HS4P2D5R, hs4m2d5r } 
		{ HS4P2D6R, hs4m2d6r } 
		{ HS4P2D7R, hs4m2d7r } 
		{ HS4P2D8R, hs4m2d8r } 

		{ HS4P2T1R, hs4m2t1r } 
		{ HS4P2T2R, hs4m2t2r } 
		{ HS4P2T3R, hs4m2t3r } 
		{ HS4P2T4R, hs4m2t4r } 
		{ HS4P2T5R, hs4m2t5r } 
		{ HS4P2T6R, hs4m2t6r } 
		{ HS4P2T7R, hs4m2t7r } 
		{ HS4P2T8R, hs4m2t8r } 
# end of horizontal_steerers


#start of vertical_steerers
		{ VS2P1D1R, vs2m1d1r } 
		{ VS2P1D2R, vs2m1d2r } 
		{ VS2P1D3R, vs2m1d3r } 
		{ VS2P1D4R, vs2m1d4r } 
		{ VS2P1D5R, vs2m1d5r } 
		{ VS2P1D6R, vs2m1d6r } 
		{ VS2P1D7R, vs2m1d7r } 
		{ VS2P1D8R, vs2m1d8r } 

		{ VS2P1T1R, vs2m1t1r } 
		{ VS2P1T2R, vs2m1t2r } 
		{ VS2P1T3R, vs2m1t3r } 
		{ VS2P1T4R, vs2m1t4r } 
		{ VS2P1T5R, vs2m1t5r } 
		{ VS2P1T6R, vs2m1t6r } 
		{ VS2P1T7R, vs2m1t7r } 
		{ VS2P1T8R, vs2m1t8r } 


# vs2m2d
		{ VS2P2D1R, vs2m2d1r } 
		{ VS2P2D2R, vs2m2d2r } 
		{ VS2P2D3R, vs2m2d3r } 
		{ VS2P2D4R, vs2m2d4r } 
		{ VS2P2D5R, vs2m2d5r } 
		{ VS2P2D6R, vs2m2d6r } 
		{ VS2P2D7R, vs2m2d7r } 
		{ VS2P2D8R, vs2m2d8r } 

		{ VS2P2T1R, vs2m2t1r } 
		{ VS2P2T2R, vs2m2t2r } 
		{ VS2P2T3R, vs2m2t3r } 
		{ VS2P2T4R, vs2m2t4r } 
		{ VS2P2T5R, vs2m2t5r } 
		{ VS2P2T6R, vs2m2t6r } 
		{ VS2P2T7R, vs2m2t7r } 
		{ VS2P2T8R, vs2m2t8r } 



# vs3m1d
		{ VS3P1D1R, vs3m1d1r } 
		{ VS3P1D2R, vs3m1d2r } 
		{ VS3P1D3R, vs3m1d3r } 
		{ VS3P1D4R, vs3m1d4r } 
		{ VS3P1D5R, vs3m1d5r } 
		{ VS3P1D6R, vs3m1d6r } 
		{ VS3P1D7R, vs3m1d7r } 
		{ VS3P1D8R, vs3m1d8r } 

		{ VS3P1T1R, vs3m1t1r } 
		{ VS3P1T2R, vs3m1t2r } 
		{ VS3P1T3R, vs3m1t3r } 
		{ VS3P1T4R, vs3m1t4r } 
		{ VS3P1T5R, vs3m1t5r } 
		{ VS3P1T6R, vs3m1t6r } 
		{ VS3P1T7R, vs3m1t7r } 
		{ VS3P1T8R, vs3m1t8r } 


# vs3m2d
		{ VS3P2D1R, vs3m2d1r } 
		{ VS3P2D2R, vs3m2d2r } 
		{ VS3P2D3R, vs3m2d3r } 
		{ VS3P2D4R, vs3m2d4r } 
		{ VS3P2D5R, vs3m2d5r } 
		{ VS3P2D6R, vs3m2d6r } 
		{ VS3P2D7R, vs3m2d7r } 
		{ VS3P2D8R, vs3m2d8r } 

		{ VS3P2T1R, vs3m2t1r } 
		{ VS3P2T2R, vs3m2t2r } 
		{ VS3P2T3R, vs3m2t3r } 
		{ VS3P2T4R, vs3m2t4r } 
		{ VS3P2T5R, vs3m2t5r } 
		{ VS3P2T6R, vs3m2t6r } 
		{ VS3P2T7R, vs3m2t7r } 
		{ VS3P2T8R, vs3m2t8r } 
# end of vertical_steerers
}
# EOF
