file db/power_converter_fanout.rec
{
	pattern {PC, ELEMENT}
#start of horizontal_steerers
		{ HS1PD1R, hs1md1r  } 
		{ HS1PD2R, hs1md2r  } 
		{ HS1PD3R, hs1md3r  } 
		{ HS1PD4R, hs1md4r  } 
		{ HS1PD5R, hs1md5r  } 
		{ HS1PD6R, hs1md6r  } 
		{ HS1PD7R, hs1md7r  } 
		{ HS1PD8R, hs1md8r  } 

		{ HS1PT1R, hs1mt1r  } 
		{ HS1PT2R, hs1mt2r  } 
		{ HS1PT3R, hs1mt3r  } 
		{ HS1PT4R, hs1mt4r  } 
		{ HS1PT5R, hs1mt5r  } 
		{ HS1PT6R, hs1mt6r  } 
		{ HS1PT7R, hs1mt7r  } 
		{ HS1PT8R, hs1mt8r  } 



# hs4m1d
		{ HS4P1D1R, hs4m1d1r } 
		{ HS4P1D2R, hs4m1d2r } 
		{ HS4P1D3R, hs4m1d3r } 
		{ HS4P1D4R, hs4m1d4r } 
		{ HS4P1D5R, hs4m1d5r } 
		{ HS4P1D6R, hs4m1d6r } 
		{ HS4P1D7R, hs4m1d7r } 
		{ HS4P1D8R, hs4m1d8r } 

		{ HS4P1T1R, hs4m1t1r } 
		{ HS4P1T2R, hs4m1t2r } 
		{ HS4P1T3R, hs4m1t3r } 
		{ HS4P1T4R, hs4m1t4r } 
		{ HS4P1T5R, hs4m1t5r } 
		{ HS4P1T6R, hs4m1t6r } 
		{ HS4P1T7R, hs4m1t7r } 
		{ HS4P1T8R, hs4m1t8r } 


# hs4m2d
		{ HS4P2D1R, hs4m2d1r } 
		{ HS4P2D2R, hs4m2d2r } 
		{ HS4P2D3R, hs4m2d3r } 
		{ HS4P2D4R, hs4m2d4r } 
		{ HS4P2D5R, hs4m2d5r } 
		{ HS4P2D6R, hs4m2d6r } 
		{ HS4P2D7R, hs4m2d7r } 
		{ HS4P2D8R, hs4m2d8r } 

		{ HS4P2T1R, hs4m2t1r } 
		{ HS4P2T2R, hs4m2t2r } 
		{ HS4P2T3R, hs4m2t3r } 
		{ HS4P2T4R, hs4m2t4r } 
		{ HS4P2T5R, hs4m2t5r } 
		{ HS4P2T6R, hs4m2t6r } 
		{ HS4P2T7R, hs4m2t7r } 
		{ HS4P2T8R, hs4m2t8r } 
# end of horizontal_steerers


#start of vertical_steerers
		{ VS2P1D1R, vs2m1d1r } 
		{ VS2P1D2R, vs2m1d2r } 
		{ VS2P1D3R, vs2m1d3r } 
		{ VS2P1D4R, vs2m1d4r } 
		{ VS2P1D5R, vs2m1d5r } 
		{ VS2P1D6R, vs2m1d6r } 
		{ VS2P1D7R, vs2m1d7r } 
		{ VS2P1D8R, vs2m1d8r } 

		{ VS2P1T1R, vs2m1t1r } 
		{ VS2P1T2R, vs2m1t2r } 
		{ VS2P1T3R, vs2m1t3r } 
		{ VS2P1T4R, vs2m1t4r } 
		{ VS2P1T5R, vs2m1t5r } 
		{ VS2P1T6R, vs2m1t6r } 
		{ VS2P1T7R, vs2m1t7r } 
		{ VS2P1T8R, vs2m1t8r } 


# vs2m2d
		{ VS2P2D1R, vs2m2d1r } 
		{ VS2P2D2R, vs2m2d2r } 
		{ VS2P2D3R, vs2m2d3r } 
		{ VS2P2D4R, vs2m2d4r } 
		{ VS2P2D5R, vs2m2d5r } 
		{ VS2P2D6R, vs2m2d6r } 
		{ VS2P2D7R, vs2m2d7r } 
		{ VS2P2D8R, vs2m2d8r } 

		{ VS2P2T1R, vs2m2t1r } 
		{ VS2P2T2R, vs2m2t2r } 
		{ VS2P2T3R, vs2m2t3r } 
		{ VS2P2T4R, vs2m2t4r } 
		{ VS2P2T5R, vs2m2t5r } 
		{ VS2P2T6R, vs2m2t6r } 
		{ VS2P2T7R, vs2m2t7r } 
		{ VS2P2T8R, vs2m2t8r } 



# vs3m1d
		{ VS3P1D1R, vs3m1d1r } 
		{ VS3P1D2R, vs3m1d2r } 
		{ VS3P1D3R, vs3m1d3r } 
		{ VS3P1D4R, vs3m1d4r } 
		{ VS3P1D5R, vs3m1d5r } 
		{ VS3P1D6R, vs3m1d6r } 
		{ VS3P1D7R, vs3m1d7r } 
		{ VS3P1D8R, vs3m1d8r } 

		{ VS3P1T1R, vs3m1t1r } 
		{ VS3P1T2R, vs3m1t2r } 
		{ VS3P1T3R, vs3m1t3r } 
		{ VS3P1T4R, vs3m1t4r } 
		{ VS3P1T5R, vs3m1t5r } 
		{ VS3P1T6R, vs3m1t6r } 
		{ VS3P1T7R, vs3m1t7r } 
		{ VS3P1T8R, vs3m1t8r } 


# vs3m2d
		{ VS3P2D1R, vs3m2d1r } 
		{ VS3P2D2R, vs3m2d2r } 
		{ VS3P2D3R, vs3m2d3r } 
		{ VS3P2D4R, vs3m2d4r } 
		{ VS3P2D5R, vs3m2d5r } 
		{ VS3P2D6R, vs3m2d6r } 
		{ VS3P2D7R, vs3m2d7r } 
		{ VS3P2D8R, vs3m2d8r } 

		{ VS3P2T1R, vs3m2t1r } 
		{ VS3P2T2R, vs3m2t2r } 
		{ VS3P2T3R, vs3m2t3r } 
		{ VS3P2T4R, vs3m2t4r } 
		{ VS3P2T5R, vs3m2t5r } 
		{ VS3P2T6R, vs3m2t6r } 
		{ VS3P2T7R, vs3m2t7r } 
		{ VS3P2T8R, vs3m2t8r } 
# end of vertical_steerers
}
# EOF
