record(fanout, "$(PREFIX):Q1PDR:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q1m1d1r:im:I")
    field(LNK1, "$(PREFIX):q1m1d2r:im:I")
    field(LNK2, "$(PREFIX):q1m1d3r:im:I")
    field(LNK3, "$(PREFIX):q1m1d4r:im:I")
    field(LNK4, "$(PREFIX):q1m1d5r:im:I")
    field(LNK5, "$(PREFIX):q1m1d6r:im:I")
    field(LNK6, "$(PREFIX):q1m1d7r:im:I")
    field(LNK7, "$(PREFIX):q1m1d8r:im:I")
    field(LNK8, "$(PREFIX):q1m2d1r:im:I")
    field(LNK9, "$(PREFIX):q1m2d2r:im:I")
    field(LNKA, "$(PREFIX):q1m2d3r:im:I")
    field(LNKB, "$(PREFIX):q1m2d4r:im:I")
    field(LNKC, "$(PREFIX):q1m2d5r:im:I")
    field(LNKD, "$(PREFIX):q1m2d6r:im:I")
    field(LNKE, "$(PREFIX):q1m2d7r:im:I")
    field(LNKF, "$(PREFIX):q1m2d8r:im:I")
}
    
record(fanout, "$(PREFIX):Q1PTR:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q1m1t1r:im:I")
    field(LNK1, "$(PREFIX):q1m1t2r:im:I")
    field(LNK2, "$(PREFIX):q1m1t3r:im:I")
    field(LNK3, "$(PREFIX):q1m1t4r:im:I")
    field(LNK4, "$(PREFIX):q1m1t5r:im:I")
    field(LNK5, "$(PREFIX):q1m1t6r:im:I")
    field(LNK6, "$(PREFIX):q1m1t7r:im:I")
    field(LNK7, "$(PREFIX):q1m1t8r:im:I")
    field(LNK8, "$(PREFIX):q1m2t1r:im:I")
    field(LNK9, "$(PREFIX):q1m2t2r:im:I")
    field(LNKA, "$(PREFIX):q1m2t3r:im:I")
    field(LNKB, "$(PREFIX):q1m2t4r:im:I")
    field(LNKC, "$(PREFIX):q1m2t5r:im:I")
    field(LNKD, "$(PREFIX):q1m2t6r:im:I")
    field(LNKE, "$(PREFIX):q1m2t7r:im:I")
    field(LNKF, "$(PREFIX):q1m2t8r:im:I")
}
    
record(fanout, "$(PREFIX):Q2PDR:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q2m1d1r:im:I")
    field(LNK1, "$(PREFIX):q2m1d2r:im:I")
    field(LNK2, "$(PREFIX):q2m1d3r:im:I")
    field(LNK3, "$(PREFIX):q2m1d4r:im:I")
    field(LNK4, "$(PREFIX):q2m1d5r:im:I")
    field(LNK5, "$(PREFIX):q2m1d6r:im:I")
    field(LNK6, "$(PREFIX):q2m1d7r:im:I")
    field(LNK7, "$(PREFIX):q2m1d8r:im:I")
    field(LNK8, "$(PREFIX):q2m2d1r:im:I")
    field(LNK9, "$(PREFIX):q2m2d2r:im:I")
    field(LNKA, "$(PREFIX):q2m2d3r:im:I")
    field(LNKB, "$(PREFIX):q2m2d4r:im:I")
    field(LNKC, "$(PREFIX):q2m2d5r:im:I")
    field(LNKD, "$(PREFIX):q2m2d6r:im:I")
    field(LNKE, "$(PREFIX):q2m2d7r:im:I")
    field(LNKF, "$(PREFIX):q2m2d8r:im:I")
}
    
record(fanout, "$(PREFIX):Q2PTR:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q2m1t1r:im:I")
    field(LNK1, "$(PREFIX):q2m1t2r:im:I")
    field(LNK2, "$(PREFIX):q2m1t3r:im:I")
    field(LNK3, "$(PREFIX):q2m1t4r:im:I")
    field(LNK4, "$(PREFIX):q2m1t5r:im:I")
    field(LNK5, "$(PREFIX):q2m1t6r:im:I")
    field(LNK6, "$(PREFIX):q2m1t7r:im:I")
    field(LNK7, "$(PREFIX):q2m1t8r:im:I")
    field(LNK8, "$(PREFIX):q2m2t1r:im:I")
    field(LNK9, "$(PREFIX):q2m2t2r:im:I")
    field(LNKA, "$(PREFIX):q2m2t3r:im:I")
    field(LNKB, "$(PREFIX):q2m2t4r:im:I")
    field(LNKC, "$(PREFIX):q2m2t5r:im:I")
    field(LNKD, "$(PREFIX):q2m2t6r:im:I")
    field(LNKE, "$(PREFIX):q2m2t7r:im:I")
    field(LNKF, "$(PREFIX):q2m2t8r:im:I")
}
    
record(fanout, "$(PREFIX):Q3P1T1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1t1r:im:I")
}
    
record(fanout, "$(PREFIX):Q3P1T6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1t6r:im:I")
}
    
record(fanout, "$(PREFIX):Q3P1T8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1t8r:im:I")
}
    
record(fanout, "$(PREFIX):Q3P2T1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m2t1r:im:I")
}
    
record(fanout, "$(PREFIX):Q3P2T6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m2t6r:im:I")
}
    
record(fanout, "$(PREFIX):Q3P2T8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m2t8r:im:I")
}
    
record(fanout, "$(PREFIX):Q3PD1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1d1r:im:I")
    field(LNK1, "$(PREFIX):q3m2d1r:im:I")
}
    
record(fanout, "$(PREFIX):Q3PD2R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1d2r:im:I")
    field(LNK1, "$(PREFIX):q3m2d2r:im:I")
}
    
record(fanout, "$(PREFIX):Q3PD3R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1d3r:im:I")
    field(LNK1, "$(PREFIX):q3m2d3r:im:I")
}
    
record(fanout, "$(PREFIX):Q3PD4R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1d4r:im:I")
    field(LNK1, "$(PREFIX):q3m2d4r:im:I")
}
    
record(fanout, "$(PREFIX):Q3PD5R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1d5r:im:I")
    field(LNK1, "$(PREFIX):q3m2d5r:im:I")
}
    
record(fanout, "$(PREFIX):Q3PD6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1d6r:im:I")
    field(LNK1, "$(PREFIX):q3m2d6r:im:I")
}
    
record(fanout, "$(PREFIX):Q3PD7R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1d7r:im:I")
    field(LNK1, "$(PREFIX):q3m2d7r:im:I")
}
    
record(fanout, "$(PREFIX):Q3PD8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1d8r:im:I")
    field(LNK1, "$(PREFIX):q3m2d8r:im:I")
}
    
record(fanout, "$(PREFIX):Q3PT2R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1t2r:im:I")
    field(LNK1, "$(PREFIX):q3m2t2r:im:I")
}
    
record(fanout, "$(PREFIX):Q3PT3R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1t3r:im:I")
    field(LNK1, "$(PREFIX):q3m2t3r:im:I")
}
    
record(fanout, "$(PREFIX):Q3PT4R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1t4r:im:I")
    field(LNK1, "$(PREFIX):q3m2t4r:im:I")
}
    
record(fanout, "$(PREFIX):Q3PT5R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1t5r:im:I")
    field(LNK1, "$(PREFIX):q3m2t5r:im:I")
}
    
record(fanout, "$(PREFIX):Q3PT7R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q3m1t7r:im:I")
    field(LNK1, "$(PREFIX):q3m2t7r:im:I")
}
    
record(fanout, "$(PREFIX):Q4P1T1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1t1r:im:I")
}
    
record(fanout, "$(PREFIX):Q4P1T6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1t6r:im:I")
}
    
record(fanout, "$(PREFIX):Q4P1T8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1t8r:im:I")
}
    
record(fanout, "$(PREFIX):Q4P2T1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m2t1r:im:I")
}
    
record(fanout, "$(PREFIX):Q4P2T6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m2t6r:im:I")
}
    
record(fanout, "$(PREFIX):Q4P2T8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m2t8r:im:I")
}
    
record(fanout, "$(PREFIX):Q4PD1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1d1r:im:I")
    field(LNK1, "$(PREFIX):q4m2d1r:im:I")
}
    
record(fanout, "$(PREFIX):Q4PD2R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1d2r:im:I")
    field(LNK1, "$(PREFIX):q4m2d2r:im:I")
}
    
record(fanout, "$(PREFIX):Q4PD3R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1d3r:im:I")
    field(LNK1, "$(PREFIX):q4m2d3r:im:I")
}
    
record(fanout, "$(PREFIX):Q4PD4R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1d4r:im:I")
    field(LNK1, "$(PREFIX):q4m2d4r:im:I")
}
    
record(fanout, "$(PREFIX):Q4PD5R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1d5r:im:I")
    field(LNK1, "$(PREFIX):q4m2d5r:im:I")
}
    
record(fanout, "$(PREFIX):Q4PD6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1d6r:im:I")
    field(LNK1, "$(PREFIX):q4m2d6r:im:I")
}
    
record(fanout, "$(PREFIX):Q4PD7R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1d7r:im:I")
    field(LNK1, "$(PREFIX):q4m2d7r:im:I")
}
    
record(fanout, "$(PREFIX):Q4PD8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1d8r:im:I")
    field(LNK1, "$(PREFIX):q4m2d8r:im:I")
}
    
record(fanout, "$(PREFIX):Q4PT2R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1t2r:im:I")
    field(LNK1, "$(PREFIX):q4m2t2r:im:I")
}
    
record(fanout, "$(PREFIX):Q4PT3R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1t3r:im:I")
    field(LNK1, "$(PREFIX):q4m2t3r:im:I")
}
    
record(fanout, "$(PREFIX):Q4PT4R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1t4r:im:I")
    field(LNK1, "$(PREFIX):q4m2t4r:im:I")
}
    
record(fanout, "$(PREFIX):Q4PT5R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1t5r:im:I")
    field(LNK1, "$(PREFIX):q4m2t5r:im:I")
}
    
record(fanout, "$(PREFIX):Q4PT7R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q4m1t7r:im:I")
    field(LNK1, "$(PREFIX):q4m2t7r:im:I")
}
    
record(fanout, "$(PREFIX):Q5P1T1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q5m1t1r:im:I")
}
    
record(fanout, "$(PREFIX):Q5P1T6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q5m1t6r:im:I")
}
    
record(fanout, "$(PREFIX):Q5P1T8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q5m1t8r:im:I")
}
    
record(fanout, "$(PREFIX):Q5P2T1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q5m2t1r:im:I")
}
    
record(fanout, "$(PREFIX):Q5P2T6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q5m2t6r:im:I")
}
    
record(fanout, "$(PREFIX):Q5P2T8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q5m2t8r:im:I")
}
    
record(fanout, "$(PREFIX):Q5PT2R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q5m1t2r:im:I")
    field(LNK1, "$(PREFIX):q5m2t2r:im:I")
}
    
record(fanout, "$(PREFIX):Q5PT3R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q5m1t3r:im:I")
    field(LNK1, "$(PREFIX):q5m2t3r:im:I")
}
    
record(fanout, "$(PREFIX):Q5PT4R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q5m1t4r:im:I")
    field(LNK1, "$(PREFIX):q5m2t4r:im:I")
}
    
record(fanout, "$(PREFIX):Q5PT5R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q5m1t5r:im:I")
    field(LNK1, "$(PREFIX):q5m2t5r:im:I")
}
    
record(fanout, "$(PREFIX):Q5PT7R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):q5m1t7r:im:I")
    field(LNK1, "$(PREFIX):q5m2t7r:im:I")
}
    
# EOF
