record(fanout, "$(PREFIX):Q1PDR:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q1M1D1R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q1M1D2R:IM:I")
    FIELD(LNK2, "$(PREFIX):Q1M1D3R:IM:I")
    FIELD(LNK3, "$(PREFIX):Q1M1D4R:IM:I")
    FIELD(LNK4, "$(PREFIX):Q1M1D5R:IM:I")
    FIELD(LNK5, "$(PREFIX):Q1M1D6R:IM:I")
    FIELD(LNK6, "$(PREFIX):Q1M1D7R:IM:I")
    FIELD(LNK7, "$(PREFIX):Q1M1D8R:IM:I")
    FIELD(LNK8, "$(PREFIX):Q1M2D1R:IM:I")
    FIELD(LNK9, "$(PREFIX):Q1M2D2R:IM:I")
    FIELD(LNKA, "$(PREFIX):Q1M2D3R:IM:I")
    FIELD(LNKB, "$(PREFIX):Q1M2D4R:IM:I")
    FIELD(LNKC, "$(PREFIX):Q1M2D5R:IM:I")
    FIELD(LNKD, "$(PREFIX):Q1M2D6R:IM:I")
    FIELD(LNKE, "$(PREFIX):Q1M2D7R:IM:I")
    FIELD(LNKF, "$(PREFIX):Q1M2D8R:im:I")
}

record(fanout, "$(PREFIX):Q1PTR:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q1M1T1R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q1M1T2R:IM:I")
    FIELD(LNK2, "$(PREFIX):Q1M1T3R:IM:I")
    FIELD(LNK3, "$(PREFIX):Q1M1T4R:IM:I")
    FIELD(LNK4, "$(PREFIX):Q1M1T5R:IM:I")
    FIELD(LNK5, "$(PREFIX):Q1M1T6R:IM:I")
    FIELD(LNK6, "$(PREFIX):Q1M1T7R:IM:I")
    FIELD(LNK7, "$(PREFIX):Q1M1T8R:IM:I")
    FIELD(LNK8, "$(PREFIX):Q1M2T1R:IM:I")
    FIELD(LNK9, "$(PREFIX):Q1M2T2R:IM:I")
    FIELD(LNKA, "$(PREFIX):Q1M2T3R:IM:I")
    FIELD(LNKB, "$(PREFIX):Q1M2T4R:IM:I")
    FIELD(LNKC, "$(PREFIX):Q1M2T5R:IM:I")
    FIELD(LNKD, "$(PREFIX):Q1M2T6R:IM:I")
    FIELD(LNKE, "$(PREFIX):Q1M2T7R:IM:I")
    FIELD(LNKF, "$(PREFIX):Q1M2T8R:im:I")
}

record(fanout, "$(PREFIX):Q2PDR:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q2M1D1R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q2M1D2R:IM:I")
    FIELD(LNK2, "$(PREFIX):Q2M1D3R:IM:I")
    FIELD(LNK3, "$(PREFIX):Q2M1D4R:IM:I")
    FIELD(LNK4, "$(PREFIX):Q2M1D5R:IM:I")
    FIELD(LNK5, "$(PREFIX):Q2M1D6R:IM:I")
    FIELD(LNK6, "$(PREFIX):Q2M1D7R:IM:I")
    FIELD(LNK7, "$(PREFIX):Q2M1D8R:IM:I")
    FIELD(LNK8, "$(PREFIX):Q2M2D1R:IM:I")
    FIELD(LNK9, "$(PREFIX):Q2M2D2R:IM:I")
    FIELD(LNKA, "$(PREFIX):Q2M2D3R:IM:I")
    FIELD(LNKB, "$(PREFIX):Q2M2D4R:IM:I")
    FIELD(LNKC, "$(PREFIX):Q2M2D5R:IM:I")
    FIELD(LNKD, "$(PREFIX):Q2M2D6R:IM:I")
    FIELD(LNKE, "$(PREFIX):Q2M2D7R:IM:I")
    FIELD(LNKF, "$(PREFIX):Q2M2D8R:im:I")
}

record(fanout, "$(PREFIX):Q2PTR:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q2M1T1R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q2M1T2R:IM:I")
    FIELD(LNK2, "$(PREFIX):Q2M1T3R:IM:I")
    FIELD(LNK3, "$(PREFIX):Q2M1T4R:IM:I")
    FIELD(LNK4, "$(PREFIX):Q2M1T5R:IM:I")
    FIELD(LNK5, "$(PREFIX):Q2M1T6R:IM:I")
    FIELD(LNK6, "$(PREFIX):Q2M1T7R:IM:I")
    FIELD(LNK7, "$(PREFIX):Q2M1T8R:IM:I")
    FIELD(LNK8, "$(PREFIX):Q2M2T1R:IM:I")
    FIELD(LNK9, "$(PREFIX):Q2M2T2R:IM:I")
    FIELD(LNKA, "$(PREFIX):Q2M2T3R:IM:I")
    FIELD(LNKB, "$(PREFIX):Q2M2T4R:IM:I")
    FIELD(LNKC, "$(PREFIX):Q2M2T5R:IM:I")
    FIELD(LNKD, "$(PREFIX):Q2M2T6R:IM:I")
    FIELD(LNKE, "$(PREFIX):Q2M2T7R:IM:I")
    FIELD(LNKF, "$(PREFIX):Q2M2T8R:im:I")
}

record(fanout, "$(PREFIX):Q3P1T1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1T1R:im:I")
}

record(fanout, "$(PREFIX):Q3P1T6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1T6R:im:I")
}

record(fanout, "$(PREFIX):Q3P1T8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1T8R:im:I")
}

record(fanout, "$(PREFIX):Q3P2T1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M2T1R:im:I")
}

record(fanout, "$(PREFIX):Q3P2T6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M2T6R:im:I")
}

record(fanout, "$(PREFIX):Q3P2T8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M2T8R:im:I")
}

record(fanout, "$(PREFIX):Q3PD1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1D1R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q3M2D1R:im:I")
}

record(fanout, "$(PREFIX):Q3PD2R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1D2R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q3M2D2R:im:I")
}

record(fanout, "$(PREFIX):Q3PD3R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1D3R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q3M2D3R:im:I")
}

record(fanout, "$(PREFIX):Q3PD4R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1D4R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q3M2D4R:im:I")
}

record(fanout, "$(PREFIX):Q3PD5R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1D5R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q3M2D5R:im:I")
}

record(fanout, "$(PREFIX):Q3PD6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1D6R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q3M2D6R:im:I")
}

record(fanout, "$(PREFIX):Q3PD7R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1D7R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q3M2D7R:im:I")
}

record(fanout, "$(PREFIX):Q3PD8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1D8R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q3M2D8R:im:I")
}

record(fanout, "$(PREFIX):Q3PT2R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1T2R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q3M2T2R:im:I")
}

record(fanout, "$(PREFIX):Q3PT3R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1T3R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q3M2T3R:im:I")
}

record(fanout, "$(PREFIX):Q3PT4R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1T4R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q3M2T4R:im:I")
}

record(fanout, "$(PREFIX):Q3PT5R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1T5R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q3M2T5R:im:I")
}

record(fanout, "$(PREFIX):Q3PT7R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q3M1T7R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q3M2T7R:im:I")
}

record(fanout, "$(PREFIX):Q4P1T1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1T1R:im:I")
}

record(fanout, "$(PREFIX):Q4P1T6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1T6R:im:I")
}

record(fanout, "$(PREFIX):Q4P1T8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1T8R:im:I")
}

record(fanout, "$(PREFIX):Q4P2T1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M2T1R:im:I")
}

record(fanout, "$(PREFIX):Q4P2T6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M2T6R:im:I")
}

record(fanout, "$(PREFIX):Q4P2T8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M2T8R:im:I")
}

record(fanout, "$(PREFIX):Q4PD1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1D1R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q4M2D1R:im:I")
}

record(fanout, "$(PREFIX):Q4PD2R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1D2R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q4M2D2R:im:I")
}

record(fanout, "$(PREFIX):Q4PD3R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1D3R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q4M2D3R:im:I")
}

record(fanout, "$(PREFIX):Q4PD4R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1D4R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q4M2D4R:im:I")
}

record(fanout, "$(PREFIX):Q4PD5R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1D5R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q4M2D5R:im:I")
}

record(fanout, "$(PREFIX):Q4PD6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1D6R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q4M2D6R:im:I")
}

record(fanout, "$(PREFIX):Q4PD7R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1D7R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q4M2D7R:im:I")
}

record(fanout, "$(PREFIX):Q4PD8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1D8R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q4M2D8R:im:I")
}

record(fanout, "$(PREFIX):Q4PT2R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1T2R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q4M2T2R:im:I")
}

record(fanout, "$(PREFIX):Q4PT3R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1T3R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q4M2T3R:im:I")
}

record(fanout, "$(PREFIX):Q4PT4R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1T4R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q4M2T4R:im:I")
}

record(fanout, "$(PREFIX):Q4PT5R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1T5R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q4M2T5R:im:I")
}

record(fanout, "$(PREFIX):Q4PT7R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q4M1T7R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q4M2T7R:im:I")
}

record(fanout, "$(PREFIX):Q5P1T1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q5M1T1R:im:I")
}

record(fanout, "$(PREFIX):Q5P1T6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q5M1T6R:im:I")
}

record(fanout, "$(PREFIX):Q5P1T8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q5M1T8R:im:I")
}

record(fanout, "$(PREFIX):Q5P2T1R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q5M2T1R:im:I")
}

record(fanout, "$(PREFIX):Q5P2T6R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q5M2T6R:im:I")
}

record(fanout, "$(PREFIX):Q5P2T8R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q5M2T8R:im:I")
}

record(fanout, "$(PREFIX):Q5PT2R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q5M1T2R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q5M2T2R:im:I")
}

record(fanout, "$(PREFIX):Q5PT3R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q5M1T3R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q5M2T3R:im:I")
}

record(fanout, "$(PREFIX):Q5PT4R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q5M1T4R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q5M2T4R:im:I")
}

record(fanout, "$(PREFIX):Q5PT5R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q5M1T5R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q5M2T5R:im:I")
}

record(fanout, "$(PREFIX):Q5PT7R:dt:fanout")
{
    field(DESC, "informing further elements")
    field(LNK0, "$(PREFIX):Q5M1T7R:IM:I")
    FIELD(LNK1, "$(PREFIX):Q5M2T7R:im:I")
}

# EOF
